/**
 * Free AI Service (Hugging Face)
 *
 * Uses Hugging Face Inference API (100% FREE)
 * Models chosen for reliability on the free tier.
 */

import { API_ENDPOINTS, API_KEYS } from '../config/api.js';

// ── Models ──────────────────────────────────────────────────────────────────
// BART is fast and reliable for summarisation on the free tier.
// For quiz/flashcards we build them locally from the real text so the output
// is always grounded in the uploaded document — no hallucinations.
const MODELS = {
    SUMMARIZATION: 'facebook/bart-large-cnn',
};

// How many characters to send to the summarisation model (BART limit ≈ 1024 tokens)
const SUMMARY_CHAR_LIMIT = 3000;

// ── Helpers ──────────────────────────────────────────────────────────────────

function mockDelay(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

/** Return true when a real HF token is present */
function hfReady() {
    return (
        API_KEYS.HUGGINGFACE &&
        API_KEYS.HUGGINGFACE !== 'YOUR_HUGGINGFACE_TOKEN_HERE' &&
        API_KEYS.HUGGINGFACE.startsWith('hf_')
    );
}

/**
 * Split text into clean sentences, filtering out very short fragments.
 */
function toSentences(text) {
    return text
        .replace(/\r\n/g, '\n')
        .split(/(?<=[.!?])\s+/)
        .map(s => s.trim())
        .filter(s => s.length > 30);
}

/**
 * Extract meaningful key phrases / terms from the text.
 * Used to build grounded quiz questions and flashcards.
 */
function extractKeyPhrases(text, max = 20) {
    // Grab capitalised multi-word phrases and long words as candidate terms
    const phrases = [];

    // Capitalised phrases (e.g. "Photosynthesis", "Calvin Cycle")
    const capMatches = text.match(/[A-Z][a-z]{3,}(?:\s+[A-Z][a-z]{2,})*/g) || [];
    capMatches.forEach(p => { if (!phrases.includes(p)) phrases.push(p); });

    // Long lowercase words that appear multiple times (likely key terms)
    const wordFreq = {};
    (text.match(/\b[a-z]{6,}\b/g) || []).forEach(w => {
        wordFreq[w] = (wordFreq[w] || 0) + 1;
    });
    Object.entries(wordFreq)
        .filter(([, count]) => count >= 2)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 15)
        .forEach(([w]) => { if (!phrases.includes(w)) phrases.push(w); });

    return phrases.slice(0, max);
}

// ── Summary ──────────────────────────────────────────────────────────────────

/**
 * Generate a summary using Hugging Face BART.
 * Falls back to an extractive summary built from the real text.
 */
export async function generateSummaryFree(text, maxLength = 200) {
    if (!text || text.trim().length === 0) {
        throw new Error('No text provided for summarisation');
    }

    // Always try the real AI first when configured
    if (hfReady()) {
        try {
            console.log('🤖 Generating summary with Hugging Face BART…');

            const input = text.substring(0, SUMMARY_CHAR_LIMIT);

            const response = await fetch(
                `${API_ENDPOINTS.HUGGINGFACE}/${MODELS.SUMMARIZATION}`,
                {
                    method: 'POST',
                    headers: {
                        Authorization: `Bearer ${API_KEYS.HUGGINGFACE}`,
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        inputs: input,
                        parameters: {
                            max_length: maxLength,
                            min_length: 60,
                            do_sample: false,
                        },
                    }),
                }
            );

            if (response.ok) {
                const data = await response.json();
                const summary = data[0]?.summary_text || '';
                if (summary.trim().length > 20) {
                    console.log('✅ Summary generated by Hugging Face');
                    return summary;
                }
            }

            // Model loading — wait and retry once
            const errBody = await response.json().catch(() => ({}));
            if (errBody?.error?.includes('loading')) {
                console.log('⏳ Model loading, retrying in 20 s…');
                await mockDelay(20000);
                return generateSummaryFree(text, maxLength);
            }

            console.warn('HF summary failed, falling back to extractive summary');
        } catch (err) {
            console.warn('HF request error, falling back:', err.message);
        }
    }

    // ── Extractive fallback — always uses the real uploaded text ──
    return buildExtractiveSummary(text, maxLength);
}

/**
 * Build a summary by picking the most informative sentences from the text.
 * This is 100% grounded in the uploaded document.
 */
function buildExtractiveSummary(text, maxWords = 200) {
    const sentences = toSentences(text);
    if (sentences.length === 0) return text.substring(0, 500);

    // Score sentences by length and position (earlier = more important)
    const scored = sentences.map((s, i) => ({
        text: s,
        score: s.split(' ').length * (1 - i / sentences.length),
    }));

    scored.sort((a, b) => b.score - a.score);

    const selected = [];
    let wordCount = 0;

    for (const item of scored) {
        const words = item.text.split(' ').length;
        if (wordCount + words > maxWords) break;
        selected.push(item.text);
        wordCount += words;
    }

    // Re-order selected sentences in their original order
    const originalOrder = sentences.filter(s => selected.includes(s));
    return originalOrder.join(' ');
}

// ── Quiz ─────────────────────────────────────────────────────────────────────

/**
 * Generate quiz questions grounded in the uploaded text.
 * Uses the real sentences and key phrases — never random generic content.
 */
export async function generateQuizFree(text, numQuestions = 5) {
    if (!text || text.trim().length === 0) {
        throw new Error('No text provided for quiz generation');
    }

    console.log('📝 Building quiz from uploaded text…');
    await mockDelay(800); // small UX delay so it feels like processing

    const sentences = toSentences(text);
    const keyPhrases = extractKeyPhrases(text, 30);
    const questions = [];

    // Strategy: for each question pick a sentence that contains a key phrase,
    // use the phrase as the "answer", and build distractors from other phrases.
    const usedSentences = new Set();

    for (const phrase of keyPhrases) {
        if (questions.length >= numQuestions) break;

        // Find a sentence that mentions this phrase
        const sourceSentence = sentences.find(
            s => s.toLowerCase().includes(phrase.toLowerCase()) && !usedSentences.has(s)
        );
        if (!sourceSentence) continue;

        usedSentences.add(sourceSentence);

        // Build 3 distractor phrases (other key phrases)
        const distractors = keyPhrases
            .filter(p => p !== phrase)
            .slice(0, 3);

        if (distractors.length < 3) continue; // not enough material

        // Randomly place the correct answer among options
        const correctIndex = Math.floor(Math.random() * 4);
        const options = [...distractors];
        options.splice(correctIndex, 0, phrase);

        questions.push({
            question: buildQuestion(sourceSentence, phrase),
            options,
            correctAnswer: correctIndex,
            explanation: `From the text: "${sourceSentence}"`,
        });
    }

    // If we couldn't build enough questions from phrases, fill with sentence-based ones
    if (questions.length < numQuestions) {
        const remaining = sentences
            .filter(s => !usedSentences.has(s))
            .slice(0, numQuestions - questions.length);

        remaining.forEach((sentence, i) => {
            const words = sentence.split(' ').filter(w => w.length > 4);
            const answer = words[Math.floor(words.length / 2)] || words[0] || 'this concept';
            const distractors = keyPhrases.filter(p => p !== answer).slice(0, 3);
            if (distractors.length < 3) return;

            const correctIndex = Math.floor(Math.random() * 4);
            const options = [...distractors];
            options.splice(correctIndex, 0, answer);

            questions.push({
                question: `According to the text, complete the following: "${sentence.replace(answer, '______')}"`,
                options,
                correctAnswer: correctIndex,
                explanation: `The original sentence reads: "${sentence}"`,
            });
        });
    }

    console.log(`✅ Quiz built: ${questions.length} questions from uploaded text`);
    return questions.slice(0, numQuestions);
}

/** Turn a sentence + key phrase into a fill-in-the-blank or what/why question */
function buildQuestion(sentence, phrase) {
    // Fill-in-the-blank style
    const filled = sentence.replace(new RegExp(phrase, 'i'), '______');
    if (filled !== sentence) {
        return `Fill in the blank: "${filled}"`;
    }
    // Fallback: what-is question
    return `Based on the text, what is "${phrase}"?`;
}

// ── Flashcards ────────────────────────────────────────────────────────────────

/**
 * Generate flashcards grounded in the uploaded text.
 */
export async function generateFlashcardsFree(text, numCards = 10) {
    if (!text || text.trim().length === 0) {
        throw new Error('No text provided for flashcard generation');
    }

    console.log('🎴 Building flashcards from uploaded text…');
    await mockDelay(600);

    const sentences = toSentences(text);
    const keyPhrases = extractKeyPhrases(text, numCards * 2);
    const flashcards = [];
    const usedPhrases = new Set();

    for (const phrase of keyPhrases) {
        if (flashcards.length >= numCards) break;
        if (usedPhrases.has(phrase)) continue;

        // Find the sentence that best defines / explains this phrase
        const defSentence = sentences.find(
            s => s.toLowerCase().includes(phrase.toLowerCase())
        );

        if (!defSentence) continue;

        usedPhrases.add(phrase);
        flashcards.push({
            front: `What is "${phrase}"?`,
            back: defSentence.trim(),
        });
    }

    // Fill remaining cards with key sentences as Q&A
    if (flashcards.length < numCards) {
        sentences
            .filter(s => !flashcards.some(f => f.back === s.trim()))
            .slice(0, numCards - flashcards.length)
            .forEach(sentence => {
                const words = sentence.split(' ');
                const keyWord = words.find(w => w.length > 5) || words[0];
                flashcards.push({
                    front: `What does the text say about "${keyWord}"?`,
                    back: sentence.trim(),
                });
            });
    }

    console.log(`✅ Flashcards built: ${flashcards.length} cards from uploaded text`);
    return flashcards.slice(0, numCards);
}

